### ISSUE TITLE
Add support for FactionsUUID

### ISSUE THREAD

**Issue by simsnet** [granny/Pl3xMap-test#15]
I had to quit using Dynmap due to performance issues and switched to Pl3xMap.  It's indeed a much better alternative; however, I'd love to see faction land on the web map.

This was possible with Dynmap & FactionsUUID, but Pl3xMap nor Pl3xMap-Claims have support for it.

**Comment by granny** [comment]
Pl3xMap will never include any support for any other plugins on it's own. That can be done through the work of an addon. Since I do not plan on maintaining the handful of addons or plugins that Billy had made, I will not update Pl3xMap-Claims to have FactionsUUID support. Either someone can take up the mantle of maintaining Pl3xMap-Claims, or FactionsUUID can add support for Pl3xMap directly.
