### ISSUE TITLE
Add Support for BeautyQuests

### ISSUE THREAD

**Issue by CptGummiball** [granny/Pl3xMap-test#19]
Hi I wanted to ask if you could add support for BeautyQuests.
I have already asked BeautyQuests and was instructed to ask you if you could set this up on your end.

Here is the link to the original issue of BeautyQuests.

https://github.com/SkytAsul/BeautyQuests/issues/303#issuecomment-1872153972

It would be great if you could set this up.

**Comment by granny** [comment]
You misunderstood. They did not ask for me to set it up on my end, but to implement the support for them into their plugin. It's not high on my priority list so there's a chance I won't get around to it, but i'll take a look eventually.

Closing this issue since it's not technically specific to pl3xmap's codebase.
