### ISSUE TITLE
Blocks fixed in #73 and #68 show as "Air"

### ISSUE THREAD

**Issue by MoiraPrime** [granny/Pl3xMap-test#74]
The blocks that weren't rendering in #73 and #68 now render, but on hover they show up as "Air".

![image](https://github.com/user-attachments/assets/1852f88d-ed6f-445c-af5a-29fa367e1809)
![image](https://github.com/user-attachments/assets/4fe42896-e105-4de7-9c40-359ae44947d6)

Edit: Forgot version number. 

Version: Pl3xMap v1.21.4-516

**Comment by granny** [comment]
Intentional because of https://github.com/granny/Pl3xMap/commit/7d043548dc6d7d642657fc9f56ca7965d7fde668. 

There's a limit to how many "indexed"  blocks and biomes can exist through the pl3xmap file protocol (Which is what allows the blockinfo to update so quickly and take up little amount of disk space).

I realized that Pl3xMap didn't need to stop registering the blocks and biomes once it reached that index limit; it can just use a default value if it can't be indexed, which is what you're seeing.

I've created a new issue here to track an improvement on how many blocks can be registered in the file protocol: https://github.com/granny/Pl3xMap/issues/75
